function [] = OSSFeatDatCreate()
% [] = OSSFeatDatCreate()
%  Function that carries out cell feature extraction on raw V & I traces
%  recorded by Derek Garden and Hugh Pastoll at NOLANLab.
%
% Last edited by Oliver Shipston-Sharman 10/06/18

attVarNames = {'spkthr',...
            'spkmax',...
            'spkhlf',...
            'rheo',...
            'ahp',...
            'vm',...
            'ir',...
            'sag',...
            'tau',...
            'resf',...
            'resmag',...
            'dvloc'};
lblVarNames = {'id',...
            'expr',...
            'age',...
            'hemi',...
            'totalcells',...
            'housing',...
            'patchdir',...
            'mlpos',...
            'rectime'};

%% Import data set. Default is to use precomputed. argin = 1 to rerun analysis.
dataset = 0; % 0=Stellate Cell data 1=Cakbindin Cell Data 2=Both

[cell_atts] = calculate_cell_atts(dataset); % Function returns features in a mouse-wise cell structure.

% Rearrange mousewise data into single matrix.
for m = 1:size(cell_atts,2)
    if m == 1
        pooled_cell_atts = cell_atts(m).mouse;
        pooled_cell_labels = cell_atts(m).labels{:}';
    else
        pooled_cell_atts = vertcat(pooled_cell_atts,cell_atts(m).mouse);
        pooled_cell_labels = [pooled_cell_labels;cell_atts(m).labels{:}'];
    end    
end

% Pooled cell atts are in numeric array..convert to table.
attT = array2table(pooled_cell_atts,'VariableNames',attVarNames);
% Pooled cell labels are experimental features e.g. dv location...convert
% to table.
lblT = cell2table(pooled_cell_labels,'VariableNames',lblVarNames);
% Concantenate table..
T = [attT,lblT];
% Save to .txt file.
writetable(T,'path_to_raw_data/OSSFeatDat.txt','Delimiter','tab');
end