function [] = OSSFeatDatCreate()
% [] = OSSFeatDatCreate()
%  Function that carries out cell feature extraction on raw V & I traces
%  recorded by Derek Garden and Hugh Pastoll at NOLANLab.
%
% Last edited by Oliver Shipston-Sharman 10/06/18

%% Import data set. Default is to use precomputed. argin = 1 to rerun analysis.
dataset = 1; % 0=Stellate Cell data 1=Calbindin Cell Data 2=Both

attVarNames = {'spkthr',...
            'spkmax',...
            'spkhlf',...
            'rheo',...
            'ahp',...
            'vm',...
            'ir',...
            'sag',...
            'tau',...
            'resf',...
            'resmag',...
            'dvloc'};

switch dataset
    case 0
        lblVarNames = {'cid',...
            'mid',...
            'expr',...
            'age',...
            'hemi',...
            'totalcells',...
            'housing',...
            'patchdir',...
            'mlpos',...
            'rectime'};
     case 1
        lblVarNames = {'cid',...
            'mid',...
            'expr',...
            'totalcells',...
            'mlpos'};
end
        
[cell_atts] = calculate_cell_atts(dataset); % Function returns features in a mouse-wise cell structure.

% Rearrange mousewise data into single matrix.
for m = 1:size(cell_atts,2)
    if m == 1
        pooled_cell_atts = cell_atts(m).mouse;
        pooled_cell_labels = cell_atts(m).labels{:}';
    else
        pooled_cell_atts = vertcat(pooled_cell_atts,cell_atts(m).mouse);
        pooled_cell_labels = [pooled_cell_labels;cell_atts(m).labels{:}'];
    end    
end

% Pooled cell atts are in numeric array.convert to table.
attT = array2table(pooled_cell_atts,'VariableNames',attVarNames);
% Pooled cell labels are experimental features e.g. dv location...convert
% to table.
lblT = cell2table(pooled_cell_labels,'VariableNames',lblVarNames);
% Concantenate table..
T = [attT,lblT];
% Save to .txt file.
switch dataset
    case 0
        tag = 'SC';
    case 1
        tag = 'PC';
    case 2
        tag = 'B';
end
writetable(T,['../../raw_data/' tag '_OSSdatatable.txt'],'Delimiter','tab');
end